
import React from 'react';
import { Avatar } from "antd";
import { Link } from "react-router-dom";
import randomColor from "randomcolor";


import './style.css';
import { isoDateToHumanReadableDate } from '../../../Util';

const LatestReportListItem = ({item}) => {
const {report_title, start, end, generatedBy = 'N/A', updated_at} = item;
const period =  `${isoDateToHumanReadableDate(start)} - ${isoDateToHumanReadableDate(end)}`
const avatarBackground = randomColor();

    return (
        <div className='LatestReportListItem'>
            <Avatar 
            style={{ backgroundColor: avatarBackground, marginRight: '20px' }}
            size="small"
            >
                {report_title?.charAt(0)?.toUpperCase() || "B"}
            </Avatar>
            <div className='item-value'>{report_title}</div>
            <div className='item-value'>{period}</div>
            <div className='item-value'>{generatedBy}</div>
            <div className='item-value'>{isoDateToHumanReadableDate(updated_at)}</div>
        </div>
    );
}
const LatestReports = (props) => {
    const {reports, allReportsUrl} = props;
    return (
        <div className='LatestReports'>
            <div className='title peacock-blue_color'>Latest Reports</div>
            <div className='list'>
                <div className='list-header mercury_border-bottom'>
                    <div className='header-item'>Title</div>
                    <div className='header-item'>Reporting Period</div>
                    <div className='header-item'>Generated By</div>
                    <div className='header-item'>Last Updated</div>
                </div>
                <div className='list-items'>
                    {reports.map((item, index) => <LatestReportListItem key={index} item={item} />)}
                </div>
                <div className='list-footer peacock-blue_color'><Link to={allReportsUrl}>View All Reports</Link></div>
                    
            </div>

        </div>
    );
}

export default LatestReports;