
import React from 'react';

import './styles.css';

const LatestReports = () => {
    return (
        <div className='LatestReports'>
            <div className='title peacock-blue_color'>Latest Reports</div>
            <div className='list'>
                <div className='list-header'>
                    <div className='header-item'>Name</div>
                    <div className='header-item'>Create At</div>
                    <div className='header-item'>Generated By</div>
                    <div className='header-item'>Last Updated</div>
                </div>
                <div className='list-items'>
                    <div className='list-item'>
                        <div>August 2021 Monthly Report</div>
                        <div>Aug 30,2021</div>
                        <div>J. Doe</div>
                        <div>Sep 10,2021</div>
                    </div>
                    <div className='list-item'>
                        <div>September 2021 Monthly Report</div>
                        <div>Sep 30,2021</div>
                        <div>J. Doe</div>
                        <div>Oct 10,2021</div>

                    </div>
                    <div className='list-item'>
                        <div>October 2021 Monthly Report</div>
                        <div>Oct 30,2021</div>
                        <div>J. Doe</div>
                        <div>Nov 10,2021</div>

                    </div>
                    <div className='list-item'>
                        <div>November 2021 Monthly Report</div>
                        <div>Nov 30,2021</div>
                        <div>J. Doe</div>
                        <div>Dec 10,2021</div>
                    </div>
                </div>
                <div className='list-footer'>View All Reports</div>
            </div>

        </div>
    );
}

export default LatestReports;